### ISSUE TITLE
Generated code execution

### ISSUE THREAD

**Issue by deepakmehta79** [approximatelabs/sketch#12]
Is it possible to directly run the code that sketch provides in an automated way. 
so user asks a question, behind the scene the code is generated and executed and the user only sees the response to his question

**Comment by bluecoconut** [comment]
Hey @deepakmehta79, you can absolutely do this pretty easily, but i didn't build it directly in due to the potential risk of calling `exec`. 

Here's an example

```python
import pandas as pd
import sketch
import random

df = pd.DataFrame(
    {   
        "transaction_id": [random.randint(1, 5121) for _ in range(20)],
        "fruit": [random.choice(["Orange", "Apple", "Banana"]) for _ in range(20)],
        "price": [random.randint(1, 323)/100 for _ in range(20)],
    }
)

code_to_run = df.sketch.howto("find the average price and standard deviation for each fruit and print it out in a nice way", call_display=False)
exec(code_to_run)
```

Note 2 things,
 (1) I use `call_display` on the sketch.howto, this means that it will return a string i can store into a variable.
 (2) I execute that code with `exec`
 
The reason i avoided including this as the default behavior was due to security implications of running code that you get generated from a model (who knows what it could do!) and also for transparency of process. 

Rather than simply assuming the AI is right, the extra copy-paste step helps bring transparency into what is happening, so any data-results can be defended!

That said, I completely understand the desire to expidite the process when you're just hacking away, so i'd suggest something like that.

Also, if you want a "step up", here's a fun snippet i just threw together:
```
@pd.api.extensions.register_dataframe_accessor("run")
class SketchHelper:
    def __init__(self, pandas_obj):
        self._obj = pandas_obj

    def __call__(self, command):
        code_to_run = self._obj.sketch.howto(command, call_display=False)
        exec(code_to_run)
```
followed by:
```
df.run("find the average price and standard deviation for each fruit and print it out in a nice way")
```
which works!~ 

Use this power at your own discretion!

**Comment by deepakmehta79** [comment]
thank you @bluecoconut, this is awesome. 
Trying to follow your suggestion but I am getting the following issue 
`2023-02-11T01:48:41.325196257Z AttributeError: 'Styler' object has no attribute 'sketch'
` Any idea how to resolve this ?

**Comment by deepakmehta79** [comment]
Hi @bluecoconut, thank you so much, this is indeed super cool. 
I am trying to following your suggesting, and trying to embed in the streamlit app but I am getting the following error:

> RuntimeError: There is no current event loop in thread 'ScriptRunner.scriptThread'.
> Traceback:
> File "/opt/conda/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
>     exec(code, module.__dict__)
> 

> import sketch
> File "/opt/conda/lib/python3.10/site-packages/sketch/__init__.py", line 2, in <module>
>     from .pandas_extension import SketchHelper  # noqa
> File "/opt/conda/lib/python3.10/site-packages/sketch/pandas_extension.py", line 16, in <module>
>     import lambdaprompt
> File "/opt/conda/lib/python3.10/site-packages/lambdaprompt/__init__.py", line 12, in <module>
>     nest_asyncio.apply()
> File "/opt/conda/lib/python3.10/site-packages/nest_asyncio.py", line 18, in apply
>     loop = loop or asyncio.get_event_loop()
> File "/opt/conda/lib/python3.10/site-packages/nest_asyncio.py", line 45, in _get_event_loop
>     loop = events.get_event_loop_policy().get_event_loop()
> File "/opt/conda/lib/python3.10/asyncio/events.py", line 656, in get_event_loop
>     raise RuntimeError('There is no current event loop in thread %r.'

**Comment by bluecoconut** [comment]
Hey @deepakmehta79 ,

This seems to be a conflict in `nest_asyncio` and `streamlit`

the fix seems to be adding a few lines to the top of the file. 

```
import asyncio

loop = asyncio.new_event_loop()
asyncio.set_event_loop(loop)
```

If you add this before `import streamlit as st` then things should work.
