### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'sketch'

### ISSUE THREAD

**Issue by Derek-Jones** [approximatelabs/sketch#17]
Just pip install sketch, and `import sketch` fails with

    File "/home/plagchk/.local/lib/python3.10/site-packages/pandas/core/generic.py", line 5902, in __getattr__
      return object.__getattribute__(self, name)
  AttributeError: 'DataFrame' object has no attribute 'sketch'

**Comment by bluecoconut** [comment]
I just tried this and it is still working for me. 

This looks like the error is related to a failed install or import of sketch. 

It might be the case that you have a local folder or package named `sketch` that is interfering and when you `import sketch`, you're getting the wrong thing?

Can you try

```python
import sketch
print(dir(sketch))
```

I get from this 
```
['Portfolio', 'SketchHelper', 'SketchPad', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'core', 'metrics', 'pandas_extension', 'references', 'sketches']
```

If you see something else, it may be due to the conflict of packages.

**Comment by Derek-Jones** [comment]
Thanks.

Just tried it on another machine and it works fine.

There must be something about my laptop that is causing this problem.
