### ISSUE TITLE
sketch.ask "Plot a bar chart..." in jupyter lab not including new lines..

### ISSUE THREAD

**Issue by lrauhockey** [approximatelabs/sketch#24]
So using sketch.ask now not returning properly...

I am getting the following
import matplotlib.pyplot as plt # Get the data for 2014 NY AGI by county df_2014 = df[df['Tax Year'] == 2014] county_agi = df_2014.groupby('County')['NY AGI of Returns'].sum() # Plot the bar chart plt.bar(county_agi.index, county_agi.values) plt.xlabel('County') plt.ylabel('NY AGI of Returns') plt.title('2014 NY AGI by County') plt.show()

What i should get is (and if i put the returns in the right spacce it works..) Funny a week ago or so it was working...
import matplotlib.pyplot as plt # Get the data for 2014 NY AGI by county 
df_2014 = df[df['Tax Year'] == 2014] 
county_agi = df_2014.groupby('County')['NY AGI of Returns'].sum() # Plot the bar chart 
plt.bar(county_agi.index, county_agi.values) 
plt.xlabel('County') 
plt.ylabel('NY AGI of Returns') 
plt.title('2014 NY AGI by County') plt.show()

**Comment by bluecoconut** [comment]
For getting code, try using `sketch.howto` rather than `sketch.ask` 

Otherwise, I don't have too much to offer in terms of quality of answers, the model in the backend is probabilistic and pulls from OpenAI, so it's not guaranteed to work. I'd say you can try phrasing your question differently / breaking the prompt into multiple steps.

**Comment by lrauhockey** [comment]
Thanks!

**Comment by lrauhockey** [comment]
worked
